import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    nav: {
      work: 'Work',
      skills: 'Skills',
      experience: 'Experience',
      certifications: 'Certifications',
      testimonials: 'Testimonials',
      contact: 'Contact',
      resume: 'Resume',
      search: 'Search',
      hireMe: 'Hire Me',
    },
    hero: {
      badge: 'Available for Global Full-Time & High-Impact Contracts',
      ctaExplore: 'Explore Projects',
      ctaContact: 'Get In Touch',
      ctaEstimator: 'Scope Estimator',
      ctaHire: 'Hire Fast-Track',
    },
    skills: {
      badge: 'Interactive Marquee Matrix',
      title: 'Core Technical Arsenal',
      desc: 'Drag, accelerate, and explore my full-stack engineering ecosystem and development tools.',
    },
    sandbox: {
      badge: 'Interactive Physics Sandbox',
      title: 'Skill Gravity Playground',
      desc: 'Grab, fling, bounce, or toss skills around the canvas with real 2D physics collisions.',
      zeroG: 'Zero-G Mode',
      gravity: 'Enable Gravity',
      hint: '💡 Touch & Fling Pills',
    },
    projects: {
      badge: 'Featured Engineering Case Studies',
      title: 'Selected Software Architecture',
      desc: 'Deep-dive into production full-stack platforms, 3D motion systems, and custom headless CMS engines.',
      allTab: 'All Projects',
      liveDemo: 'Live Demo',
      caseStudy: 'Case Study',
      github: 'Source Code',
    },
    radar: {
      badge: 'Empirical Engineering Benchmarks',
      title: 'Architecture & Performance Radar',
      desc: 'A multi-dimensional evaluation of full-stack scalability, real-time throughput, and production engineering rigor.',
      clickHint: '⚡ Click any node to inspect architectural metrics',
      lighthouseTitle: 'Google Lighthouse Score',
      certified: '100% Green Certified',
    },
    code: {
      badge: 'Interactive Code Execution',
      title: 'Architecture & Live Code Snippets',
      desc: 'Select a core module below and click "Run Snippet" to test live simulated execution in the runtime terminal.',
      runBtn: 'Run Snippet',
      consoleTitle: 'Live Execution Console:',
      executing: 'Executing...',
      done: 'Done (Exit Code 0)',
    },
    github: {
      badge: 'Live GitHub API Activity',
      title: 'Open-Source & GitHub Cadence',
      desc: 'Real-time repository statistics, commit density, and public repository showcase synced from GitHub API.',
      totalRepos: 'Public Repositories',
      commitsCount: '2026 Commit Activity',
      recentStars: 'GitHub Stars',
      viewProfile: 'View GitHub Profile',
    },
    timeline: {
      badge: 'Career Scrollytelling',
      title: 'Journey & Milestones',
      desc: 'A chronological timeline of career milestones, leadership roles, and major engineering accomplishments.',
    },
    certificates: {
      badge: 'Verified Accreditations',
      title: 'Certifications & Honors',
      desc: 'Official professional licenses and industry certifications from global tech institutions.',
      verifyBtn: 'Verify Credential',
    },
    testimonials: {
      badge: 'Peer Endorsements',
      title: 'Recommendations & Trust',
      desc: 'Testimonials and feedback from engineering directors, startup founders, and collaborative peers.',
      leaveReview: '✨ Leave a Recommendation',
    },
    contact: {
      badge: 'Initiate Collaboration',
      title: "Let's Build Something Exceptional Together",
      desc: 'Have an engineering role or a project briefing? Send a message and I will reply within 24 hours.',
      nameLabel: 'Your Full Name *',
      emailLabel: 'Your Email *',
      msgLabel: 'Message / Project Scope *',
      namePlaceholder: 'Noman Nawaz',
      emailPlaceholder: 'your.email@company.com',
      msgPlaceholder: 'Tell me about your project, timeline, or engineering role requirements...',
      sendBtn: 'Send Message',
      sendingBtn: 'Transmitting Message...',
      successMsg: 'Message transmitted successfully! I will reply shortly.',
    },
    footer: {
      tagline: 'Crafted with React 19, Node.js, MongoDB Atlas, and Tailwind CSS v4.',
      copyright: 'All Rights Reserved.',
      backToTop: 'Back to Top',
    },
  },
  ur: {
    nav: {
      work: 'پروجیکٹس',
      skills: 'مہارتیں',
      experience: 'تجربہ',
      certifications: 'اسناد',
      testimonials: 'آراء',
      contact: 'رابطہ',
      resume: 'سی وی',
      search: 'تلاش',
      hireMe: 'ہائر کریں',
    },
    hero: {
      badge: 'عالمی ملازمت اور پروجیکٹس کے لیے دستیاب',
      ctaExplore: 'پروجیکٹس دیکھیں',
      ctaContact: 'رابطہ کریں',
      ctaEstimator: 'پروجیکٹ تخمینہ',
      ctaHire: 'فوری ہائرنگ',
    },
    skills: {
      badge: 'انٹرایکٹو ٹولز لسٹ',
      title: 'تکنیکی مہارتیں اور ٹولز',
      desc: 'پروگرامنگ زبانوں، بیک اینڈ سروسز، ری ایکٹو فرنٹ اینڈز اور ڈیٹا بیس سسٹمز کا جدید ترین مجموعہ۔',
    },
    sandbox: {
      badge: 'طبیعیاتی سینڈ باکس',
      title: 'اسکلز کشش ثقل پلے گراؤنڈ',
      desc: 'مہارتوں کے پِلز کو پکڑیں، اچھالیں اور حقیقت پسندانہ فزکس کا تجربہ کریں۔',
      zeroG: 'زیرو گریویٹی',
      gravity: 'کشش ثقل فعال کریں',
      hint: '💡 ٹچ کر کے اچھالیں',
    },
    projects: {
      badge: 'منتخب سافٹ ویئر کیس اسٹڈیز',
      title: 'بہترین سافٹ ویئر آرکیٹیکچر',
      desc: 'فل اسٹیک ایپلی کیشنز اور کسٹم ہیڈلیس سی ایم ایس سسٹمز کی تفصیلات دیکھیں۔',
      allTab: 'تمام پروجیکٹس',
      liveDemo: 'لائیو ڈیمو',
      caseStudy: 'کیس اسٹڈی',
      github: 'سور کوڈ',
    },
    radar: {
      badge: 'انجینئرنگ کی کارکردگی کا ڈیٹا',
      title: 'آرکیٹیکچر اور اسپیڈ ریڈار',
      desc: 'مختلف فل اسٹیک شعبوں میں رفتار، اسکیلنگ اور سیکیورٹی کا معیار۔',
      clickHint: '⚡ کسی بھی پوائنٹ پر کلک کر کے تفصیل دیکھیں',
      lighthouseTitle: 'گوگل لائٹ ہاؤس اسکور',
      certified: '100% تصدیق شدہ',
    },
    code: {
      badge: 'لائیو کوڈ ایگزیکیوشن',
      title: 'انٹرایکٹو کوڈ اسنیپٹس',
      desc: 'کسی بھی ماڈیول کا انتخاب کریں اور رن بٹن دبا کر لائیو کنسول آؤٹ پٹ دیکھیں۔',
      runBtn: 'اسنیپٹ چلائیں',
      consoleTitle: 'لائیو کنسول آؤٹ پٹ:',
      executing: 'چل رہا ہے...',
      done: 'مکمل (کوڈ 0)',
    },
    github: {
      badge: 'گٹ ہب اوپن سورس لائیو ڈیٹا',
      title: 'گٹ ہب اوپن سورس سرگرمیاں',
      desc: 'ریئل ٹائم ریپوزٹریز، کمٹ فریکوئنسی اور اسٹارز کی لائیو تفصیلات۔',
      totalRepos: 'پبلک ریپوزٹریز',
      commitsCount: '2026 کمٹ سرگرمیاں',
      recentStars: 'گٹ ہب اسٹارز',
      viewProfile: 'پروفائل دیکھیں',
    },
    timeline: {
      badge: 'کیریئر کا سفر',
      title: 'سنگ میل اور کامیابیاں',
      desc: 'کیریئر، تعلیم اور پروفیشنل لیڈرشپ کے تمام اہم سنگ میل۔',
    },
    certificates: {
      badge: 'تصدیق شدہ اسناد',
      title: 'سرٹیفکیٹس اور اعزازات',
      desc: 'عالمی ٹیک اداروں سے جاری کردہ باضابطہ تصدیق شدہ سرٹیفکیٹس۔',
      verifyBtn: 'سند کی تصدیق',
    },
    testimonials: {
      badge: 'کلائنٹس کے تاثرات',
      title: 'آراء اور اعتمادات',
      desc: 'انجینئرنگ مینیجرز اور کلائنٹس کے تصدیق شدہ بیانات۔',
      leaveReview: '✨ اپنی رائے دیں',
    },
    contact: {
      badge: 'رابطہ کا آغاز',
      title: 'آئیے مل کر کچھ شاندار بناتے ہیں',
      desc: 'کیا آپ کے پاس کوئی پروجیکٹ یا ملازمت کا موقع ہے؟ میسج بھیجیں میں 24 گھنٹوں میں جواب دوں گا۔',
      nameLabel: 'آپ کا پورا نام *',
      emailLabel: 'آپ کی ای میل *',
      msgLabel: 'پروجیکٹ کی تفصیل *',
      namePlaceholder: 'نعمان نواز',
      emailPlaceholder: 'your.email@company.com',
      msgPlaceholder: 'اپنے پروجیکٹ کی ضروریات اور تفصیلات بتائیں...',
      sendBtn: 'پیغام بھیجیں',
      sendingBtn: 'بھیجا جا رہا ہے...',
      successMsg: 'پیغام موصول ہو گیا! میں جلد رابطہ کروں گا۔',
    },
    footer: {
      tagline: 'ری ایکٹ 19، نوڈ جے ایس، مونگو ڈی بی اور ٹیل ونڈ کے ساتھ تیار کردہ۔',
      copyright: 'جملہ حقوق محفوظ ہیں۔',
      backToTop: 'اوپر جائیں',
    },
  },
  de: {
    nav: {
      work: 'Projekte',
      skills: 'Skills',
      experience: 'Erfahrung',
      certifications: 'Zertifikate',
      testimonials: 'Referenzen',
      contact: 'Kontakt',
      resume: 'Lebenslauf',
      search: 'Suche',
      hireMe: 'Anstellen',
    },
    hero: {
      badge: 'Verfügbar für weltweite Vollzeit- & Projektverträge',
      ctaExplore: 'Projekte Entdecken',
      ctaContact: 'Kontakt Aufnehmen',
      ctaEstimator: 'Umfangsrechner',
      ctaHire: 'Direkt Anfragen',
    },
    skills: {
      badge: 'Technologie-Matrix',
      title: 'Technologisches Arsenal',
      desc: 'Ein kuratiertes Inventar aus modernen Programmiersprachen, Cloud-Architekturen und reaktiven Benutzeroberflächen.',
    },
    sandbox: {
      badge: 'Physikalischer Sandkasten',
      title: 'Skill-Gravitations-Spielplatz',
      desc: 'Interaktive Skill-Pillen mit echter 2D-Kollisionsphysik und Trägheit.',
      zeroG: 'Schwerelosigkeit',
      gravity: 'Gravitation an',
      hint: '💡 Berühren & Werfen',
    },
    projects: {
      badge: 'Ausgewählte Fallstudien',
      title: 'Software-Architektur & Projekte',
      desc: 'Hochperformante Full-Stack-Webanwendungen und maßgeschneiderte Headless CMS Systeme.',
      allTab: 'Alle Projekte',
      liveDemo: 'Live-Demo',
      caseStudy: 'Fallstudie',
      github: 'Quellcode',
    },
    radar: {
      badge: 'Empirische Benchmarks',
      title: 'Architektur- & Performance-Radar',
      desc: 'Mehrdimensionale Bewertung von Full-Stack-Skalierbarkeit und Durchsatz.',
      clickHint: '⚡ Klicken Sie auf einen Punkt für Details',
      lighthouseTitle: 'Google Lighthouse Score',
      certified: '100% Grün Zertifiziert',
    },
    code: {
      badge: 'Interaktive Code-Ausführung',
      title: 'Architektur & Live-Snippets',
      desc: 'Wählen Sie ein Modul und führen Sie simulierte Code-Snippets in Echtzeit aus.',
      runBtn: 'Snippet Ausführen',
      consoleTitle: 'Live-Ausführungskonsole:',
      executing: 'Wird ausgeführt...',
      done: 'Fertig (Code 0)',
    },
    github: {
      badge: 'Live GitHub Aktivität',
      title: 'Open-Source & GitHub-Kadenz',
      desc: 'Echtzeit-Repository-Statistiken und Commit-Aktivitäten via GitHub API.',
      totalRepos: 'Öffentliche Repositories',
      commitsCount: 'Commit-Aktivität 2026',
      recentStars: 'GitHub Sterne',
      viewProfile: 'Profil Anzeigen',
    },
    timeline: {
      badge: 'Beruflicher Werdegang',
      title: 'Stationen & Meilensteine',
      desc: 'Chronologische Übersicht über Berufserfahrung und wichtige Meilensteine.',
    },
    certificates: {
      badge: 'Verifizierte Zertifizierungen',
      title: 'Zertifikate & Auszeichnungen',
      desc: 'Offizielle Zertifikate globaler Technologie-Institute.',
      verifyBtn: 'Zertifikat Verifizieren',
    },
    testimonials: {
      badge: 'Kundenstimmen',
      title: 'Empfehlungen & Vertrauen',
      desc: 'Referenzen und Bewertungen von Engineering-Leitern und Gründern.',
      leaveReview: '✨ Empfehlung Abgeben',
    },
    contact: {
      badge: 'Zusammenarbeit Starten',
      title: 'Lassen Sie uns Großes erschaffen',
      desc: 'Haben Sie ein Projekt oder eine offene Stelle? Ich antworte innerhalb von 24 Stunden.',
      nameLabel: 'Vollständiger Name *',
      emailLabel: 'E-Mail-Adresse *',
      msgLabel: 'Projektbeschreibung *',
      namePlaceholder: 'Noman Nawaz',
      emailPlaceholder: 'ihre.email@firma.de',
      msgPlaceholder: 'Beschreiben Sie Ihre Anforderungen oder Ihr Projekt...',
      sendBtn: 'Nachricht Senden',
      sendingBtn: 'Wird übermittelt...',
      successMsg: 'Nachricht erfolgreich empfangen! Ich antworte in Kürze.',
    },
    footer: {
      tagline: 'Entwickelt mit React 19, Node.js, MongoDB Atlas und Tailwind CSS v4.',
      copyright: 'Alle Rechte vorbehalten.',
      backToTop: 'Nach oben',
    },
  },
  es: {
    nav: {
      work: 'Proyectos',
      skills: 'Habilidades',
      experience: 'Experiencia',
      certifications: 'Certificados',
      testimonials: 'Testimonios',
      contact: 'Contacto',
      resume: 'Currículum',
      search: 'Buscar',
      hireMe: 'Contratar',
    },
    hero: {
      badge: 'Disponible para contratos remotos globales y tiempo completo',
      ctaExplore: 'Explorar Proyectos',
      ctaContact: 'Contactar',
      ctaEstimator: 'Estimador',
      ctaHire: 'Contratar',
    },
    skills: {
      badge: 'Matriz Tecnológica',
      title: 'Arsenal Tecnológico',
      desc: 'Un inventario de lenguajes de programación, backend escalables y frontend reactivos.',
    },
    sandbox: {
      badge: 'Sandbox de Física',
      title: 'Campo de Gravedad de Habilidades',
      desc: 'Interactúa con pastillas de habilidades usando física de colisiones 2D real.',
      zeroG: 'Modo Cero-G',
      gravity: 'Activar Gravedad',
      hint: '💡 Toca y Lanza',
    },
    projects: {
      badge: 'Estudios de Caso de Ingeniería',
      title: 'Arquitectura de Software y Proyectos',
      desc: 'Aplicaciones web de alto rendimiento y arquitecturas empresariales modernas.',
      allTab: 'Todos los Proyectos',
      liveDemo: 'Demo en Vivo',
      caseStudy: 'Estudio de Caso',
      github: 'Código Fuente',
    },
    radar: {
      badge: 'Métricas de Ingeniería Empíricas',
      title: 'Radar de Arquitectura y Rendimiento',
      desc: 'Evaluación multidimensional de escalabilidad y rendimiento full-stack.',
      clickHint: '⚡ Haz clic en cualquier nodo para ver detalles',
      lighthouseTitle: 'Puntuación Google Lighthouse',
      certified: '100% Certificado en Verde',
    },
    code: {
      badge: 'Ejecución de Código en Vivo',
      title: 'Código en Vivo y Fragmentos',
      desc: 'Selecciona un módulo y ejecuta código simulado en tiempo real.',
      runBtn: 'Ejecutar Fragmento',
      consoleTitle: 'Consola de Ejecución en Vivo:',
      executing: 'Ejecutando...',
      done: 'Completado (Código 0)',
    },
    github: {
      badge: 'Actividad en Vivo de GitHub API',
      title: 'Actividad en GitHub y Código Abierto',
      desc: 'Estadísticas de repositorios en tiempo real y commits sincronizados con la API de GitHub.',
      totalRepos: 'Repositorios Públicos',
      commitsCount: 'Actividad de Commits 2026',
      recentStars: 'Estrellas en GitHub',
      viewProfile: 'Ver Perfil en GitHub',
    },
    timeline: {
      badge: 'Trayectoria Profesional',
      title: 'Trayectoria y Logros',
      desc: 'Cronología de experiencia laboral, roles de liderazgo y logros técnicos.',
    },
    certificates: {
      badge: 'Acreditaciones Verificadas',
      title: 'Certificaciones y Honores',
      desc: 'Licencias profesionales oficiales de instituciones tecnológicas globales.',
      verifyBtn: 'Verificar Credencial',
    },
    testimonials: {
      badge: 'Recomendaciones',
      title: 'Recomendaciones de Clientes',
      desc: 'Testimonios de directores de ingeniería y fundadores de startups.',
      leaveReview: '✨ Dejar una Recomendación',
    },
    contact: {
      badge: 'Iniciar Colaboración',
      title: 'Construyamos algo extraordinario',
      desc: '¿Tienes un proyecto de alto impacto? Escríbeme y responderé en 24 horas.',
      nameLabel: 'Tu Nombre Completo *',
      emailLabel: 'Tu Correo Electrónico *',
      msgLabel: 'Mensaje o Alcance del Proyecto *',
      namePlaceholder: 'Noman Nawaz',
      emailPlaceholder: 'tu.correo@empresa.com',
      msgPlaceholder: 'Cuéntame sobre los requisitos de tu proyecto o rol...',
      sendBtn: 'Enviar Mensaje',
      sendingBtn: 'Enviando Mensaje...',
      successMsg: '¡Mensaje recibido! Me pondré en contacto contigo pronto.',
    },
    footer: {
      tagline: 'Desarrollado con React 19, Node.js, MongoDB Atlas y Tailwind CSS v4.',
      copyright: 'Todos los derechos reservados.',
      backToTop: 'Volver Arriba',
    },
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('noman_lang') || 'en';
  });

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
      localStorage.setItem('noman_lang', newLang);
    }
  };

  const t = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;
